name: DRL_HW04
channels:
  - defaults
dependencies:
  - python=3.7
  - tensorflow=2.6.0
  - tensorflow-probability=0.14.0
  - swig
  - imageio
  - matplotlib
  - jupyter
  - pip
  - pip:
    - gym
    - gym[box2d]
